name: shell commands
on:
  - push
env:
  AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}
  AWS SECRET ACCESS KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
jobs:
  terraform-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@vi
      - name: Set Terraform
        uses: hashicorp/setup-terraform@v2 
        with:
          terraform_version: 1.1.9
      - name: Terraform init
        run: terraform init 
      - name: Terraform fmt
        run: terraform fmt
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan 
        run: terraform plan
      - name: Terraform apply
        run: terraform apply -auto-approve 
      - name: Terraform destroy
        run: terraform destroy -auto-approve